-- Create items table
CREATE TABLE IF NOT EXISTS items (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    IMG_PATH VARCHAR(255),
    PRICE BIGINT NOT NULL
);

-- Create cart_items table
CREATE TABLE IF NOT EXISTS cart_items (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ITEM_ID BIGINT NOT NULL,
    COUNT INTEGER NOT NULL,
    FOREIGN KEY (ITEM_ID) REFERENCES items(ID) ON DELETE CASCADE
);

-- Create orders table
CREATE TABLE IF NOT EXISTS orders (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TOTAL_SUM BIGINT NOT NULL
);

-- Create order_items table
CREATE TABLE IF NOT EXISTS order_items (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    COUNT INTEGER NOT NULL,
    PRICE BIGINT NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES orders(ID) ON DELETE CASCADE,
    FOREIGN KEY (ITEM_ID) REFERENCES items(ID) ON DELETE CASCADE
);

